// AUTO-GENERATED by scripts/generate-api-map.mjs
// Source: backend src/index.ts + src/routes/*.ts

export const backendRouteMap = [
  {
    "method": "GET",
    "path": "/api/admin/change-requests",
    "sourceFile": "src/routes/admin.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/change-requests/:changeRequestId/review",
    "sourceFile": "src/routes/admin.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/submissions/:submissionId/review",
    "sourceFile": "src/routes/admin.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/work-items",
    "sourceFile": "src/routes/admin.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/work-items/:workItemId",
    "sourceFile": "src/routes/admin.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/login",
    "sourceFile": "src/routes/auth.ts"
  },
  {
    "method": "POST",
    "path": "/api/submissions/:submissionId/files",
    "sourceFile": "src/routes/submissions.ts"
  },
  {
    "method": "POST",
    "path": "/api/submissions/:submissionId/finalize",
    "sourceFile": "src/routes/submissions.ts"
  },
  {
    "method": "GET",
    "path": "/api/submissions/:submissionId/status",
    "sourceFile": "src/routes/submissions.ts"
  },
  {
    "method": "POST",
    "path": "/api/work-items/",
    "sourceFile": "src/routes/workItems.ts"
  },
  {
    "method": "GET",
    "path": "/api/work-items/:workItemId",
    "sourceFile": "src/routes/workItems.ts"
  },
  {
    "method": "GET",
    "path": "/api/work-items/:workItemId/change-requests",
    "sourceFile": "src/routes/workItems.ts"
  },
  {
    "method": "POST",
    "path": "/api/work-items/:workItemId/change-requests",
    "sourceFile": "src/routes/workItems.ts"
  },
  {
    "method": "POST",
    "path": "/api/work-items/:workItemId/submissions",
    "sourceFile": "src/routes/submissions.ts"
  },
  {
    "method": "GET",
    "path": "/api/work-items/me",
    "sourceFile": "src/routes/workItems.ts"
  }
] as const;
