import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

function normalizeRoute(route) {
  return route.replace(/\/{2,}/g, "/");
}

async function main() {
  const frontendRoot = process.cwd();
  const backendRoot = path.resolve(frontendRoot, "..");
  const backendSrcRoot = path.join(backendRoot, "src");
  const routesDir = path.join(backendSrcRoot, "routes");
  const backendIndexPath = path.join(backendSrcRoot, "index.ts");

  const indexCode = await readFile(backendIndexPath, "utf8");
  const routerPrefixMap = new Map();
  for (const match of indexCode.matchAll(/app\.use\("([^"]+)",\s*(\w+)\)/g)) {
    routerPrefixMap.set(match[2], match[1]);
  }

  const routeFiles = (await readdir(routesDir))
    .filter((name) => name.endsWith(".ts"))
    .sort();

  const entries = [];
  for (const file of routeFiles) {
    const fullPath = path.join(routesDir, file);
    const source = await readFile(fullPath, "utf8");
    const routerMatch = source.match(/export const (\w+) = Router\(\)/);
    if (!routerMatch) {
      continue;
    }
    const routerName = routerMatch[1];
    const prefix = routerPrefixMap.get(routerName) ?? "";

    const routeRegex = new RegExp(
      String.raw`${routerName}\.(get|post|put|patch|delete)\(\s*"([^"]+)"`,
      "g",
    );
    for (const routeMatch of source.matchAll(routeRegex)) {
      entries.push({
        method: routeMatch[1].toUpperCase(),
        path: normalizeRoute(`${prefix}${routeMatch[2]}`),
        sourceFile: `src/routes/${file}`,
      });
    }
  }

  entries.sort((a, b) => {
    if (a.path === b.path) {
      return a.method.localeCompare(b.method);
    }
    return a.path.localeCompare(b.path);
  });

  const outputPath = path.join(frontendRoot, "src", "lib", "api", "generated-routes.ts");
  await mkdir(path.dirname(outputPath), { recursive: true });
  const body = `// AUTO-GENERATED by scripts/generate-api-map.mjs
// Source: backend src/index.ts + src/routes/*.ts

export const backendRouteMap = ${JSON.stringify(entries, null, 2)} as const;
`;
  await writeFile(outputPath, body, "utf8");
  console.log(`Generated ${entries.length} routes -> ${path.relative(frontendRoot, outputPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
